In [28]:
import prody as pr

base = '/home/lorenzo/deep_apbs/srcData/pdbbind_v2019_refined'
name = '1a1e'
file = f'{base}/{name}/{name}_protein.pdb'

structure = pr.parsePDB(file)
structure

<AtomGroup: 1a1e_protein (3279 atoms)>

In [21]:
structure.getCoords().mean(axis=0)

array([42.66277646, 10.68376822, 30.48335102])

In [22]:
coords = structure.getCoords()

In [23]:
import scipy
import numpy as np
from scipy.spatial.transform import Rotation
coords.mean(axis=0)

array([42.66277646, 10.68376822, 30.48335102])

In [24]:
r = Rotation.random().as_matrix()

In [29]:
coords2 = np.einsum('ij,kj->ki', r, coords)
structure2 = structure.copy()
structure2.setCoords(coords2)

dst = f'{base}/{name}/{name}_rotated.pdb'
pr.writePDB(dst, structure2)

'/home/lorenzo/deep_apbs/srcData/pdbbind_v2019_refined/1a1e/1a1e_rotated.pdb'

In [27]:
structure2.getCoords().mean(axis=0)

array([ -7.30299945, -33.14711497,  41.36937341])

In [9]:
coords.mean(axis=0)

array([42.66277646, 10.68376822, 30.48335102])

In [42]:
((coords - coords.mean(axis=0))**2).sum()

42960.029711536896

In [43]:
((coords2 - coords2.mean(axis=0))**2).sum()

42960.0297115369

In [36]:
coords2.mean(axis=0)

array([18.62146267, 19.00431087, 50.17221991])

In [37]:
np.einsum('ij,j->i', r, coords.mean(axis=0))

array([18.62146267, 19.00431087, 50.17221991])

In [10]:
np.dot(r2, np.transpose(r2))

NameError: name 'r2' is not defined